// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG1th_YKAjGWz3PQBaaLyZOx-WgowliG8',
    appId: '1:199061755150:web:9035b269e954164b4b735f',
    messagingSenderId: '199061755150',
    projectId: 'flutter-notes-app-cfc0b',
    authDomain: 'flutter-notes-app-cfc0b.firebaseapp.com',
    storageBucket: 'flutter-notes-app-cfc0b.appspot.com',
    measurementId: 'G-88FGKDSC76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_5XxR0OWLRdFE-BuvqpHfE472VuO078',
    appId: '1:199061755150:android:cd05a4191f6b56b24b735f',
    messagingSenderId: '199061755150',
    projectId: 'flutter-notes-app-cfc0b',
    storageBucket: 'flutter-notes-app-cfc0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2--UFTASijFiUe6tvkH5oruHfWVfcT0',
    appId: '1:199061755150:ios:b635d8a31f6d73c84b735f',
    messagingSenderId: '199061755150',
    projectId: 'flutter-notes-app-cfc0b',
    storageBucket: 'flutter-notes-app-cfc0b.appspot.com',
    iosClientId: '199061755150-n2eamgl3vufm0fam9jcbdekoil3su48m.apps.googleusercontent.com',
    iosBundleId: 'com.queuelyte.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2--UFTASijFiUe6tvkH5oruHfWVfcT0',
    appId: '1:199061755150:ios:b635d8a31f6d73c84b735f',
    messagingSenderId: '199061755150',
    projectId: 'flutter-notes-app-cfc0b',
    storageBucket: 'flutter-notes-app-cfc0b.appspot.com',
    iosClientId: '199061755150-n2eamgl3vufm0fam9jcbdekoil3su48m.apps.googleusercontent.com',
    iosBundleId: 'com.queuelyte.notesApp',
  );
}
